# fly.toml app configuration file generated for vgc-live-battle-calculator on 2026-10-01T18:38:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vgc-live-battle-calculator'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  VGC_SOLVER_WORKERS = '3'
  VGC_SOLVE_MAX_DEPTH = '3'

[[mounts]]
  source = 'vgc_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 15

[[vm]]
  size = 'shared-cpu-4x'
  memory = '2gb'
